plugins = []
headers = []
redirects = []

[build]
edge_functions = "C:\\Users\\ludas\\.gemini\\antigravity\\scratch\\fastly-edge-speedtest\\probes\\netlify_probe\\netlify\\edge-functions"
publish = "C:\\Users\\ludas\\.gemini\\antigravity\\scratch\\fastly-edge-speedtest\\probes\\netlify_probe"
publishOrigin = "default"
base = "C:\\Users\\ludas\\.gemini\\antigravity\\scratch\\fastly-edge-speedtest\\probes\\netlify_probe"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[edge_functions]]
path = "/tcp-test"
function = "tcp-test"

[functions]

[functions."*"]