name: Edge Anycast Cloud Speedtest

on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  cloud-speedtest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run Cloud Anycast Speedtest
        run: |
          python speedtest.py

      - name: Commit and Push Updates
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add clash.yaml clash_fastly.yaml clash_wasmer.yaml clash_netlify.yaml fastly_best_nodes.json README.md
          git diff --quiet && git diff --staged --quiet || (git commit -m "chore(auto): update cloud-tested anycast nodes [skip ci]" && git pull --rebase origin main && git push origin main)
